# Generated by Django 4.0.6 on 2022-08-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcode',
            name='district',
        ),
        migrations.AddField(
            model_name='postcode',
            name='post_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcodess', to='setting.postoffice'),
        ),
    ]
